### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by JamieSlome** [requirejs/r.js#1012]
Hey there!

I belong to an open source security research community, and a member (@sampaguitas) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jrburke** [comment]
SECURITY.md file has been added.

**Comment by JamieSlome** [comment]
@jrburke - thanks for the response! 🎉 

Just for reference, you can view the report directly here:
https://huntr.dev/bounties/c5eec66c-e82b-4678-ad32-2517236ab3e5/

It is private and only accessible to maintainers with repository write permissions! ❤️

**Comment by jrburke** [comment]
I’m assuming a plain text version of the report will be sent via the guidance in the SECURITY.md file.

**Comment by Sampaguitas** [comment]
hi @jrburke, I have sent you the plain text version of the report.
