### ISSUE TITLE
Traced output with contents as a data structure for use by source map tooling

### ISSUE THREAD

**Issue by eleith** [requirejs/r.js#783]
when listening to `onBuildWrite`, i expected contents to be the actual content that will be built by the optimizer.

however, i noticed that with plugins like require.css, the content i get is just the file itself and not the what eventually gets written out (css will be embedded).

so while require.js writes out a module with the CSS injected inline, `onBuildWrite` passes in the contents that is just straight from the file itself.

is this intended? is their another function i can hook into that will show me the final content of the module?

i'm trying to listen to each piece that gets concated into the file so i can build a sourceMap for it. we run our uglify in a separate process and we don't want requirejs to run uglify for us (and thus we have to generate the sourceMap ourselves instead of relying on requirejs to do it)

**Comment by eleith** [comment]
digging into r.js, the reason is that plugins are run at the end and `onLayerEnd` is called. but no `onBuildWrite` is executed for the output from these plugins.

**Comment by jrburke** [comment]
First thought is that this was just an oversight, but will need to dive into it more to be sure. Putting it in the 2.1.17 bucket.

**Comment by eleith** [comment]
it's not a perfect fit in some ways, because onBuildWrite passes in a filename, modulename and contents. for plugins, a filename doesn't always make sense (particularly with require.css)

i'm working with an internal fork that just calls onBuildWrite in the `onLayerEnd` loop. doesn't feel like a general solution though that is worth pushing upstream.

**Comment by eleith** [comment]
my goal was to hook our build tool into r.js so we can write our own sourcemaps. we have a streaming build and need other customizations that the sourcemap feature of r.js did not meet our needs. 

what we ended up doing is writing our own hook `onBuildWriteJS` into two places. the serialization `prim` and the looping of plugins `onLayerEnd`. from there, we are able to parse every piece of our final build.js file and build a working sourcemap (preserving sourceContents) and more.

we've got it working. but we had to patch r.js in order to get the hooks in the right places.

the `onBuildWrite` function seems like it does what it is meant to do, which is to allow the user to change up the contents of non-plugin dependencies. so i'll close this ticket, but leave you with the suggestion for a new hook that is more focused on someone wanting to just parse the entire r.js, independent of where it came from.

**Comment by jrburke** [comment]
I would be interested in learning more, like where the calls were inserted specifically. Feel free to do a pull request that does not have to be functional, can just be a comment with what was inserted.

While onBuildWrite might be doing what is expected from it, i think it is reasonable for code that might want to do onwrite actions to get a shot at the plugin resources placed in a build.

So I am going to leave this open for a bit to still consider that. Totally fine if you think this was too custom and do not want to talk about it more, this will be more of a reminder for myself to check plugin resource pathways as related to onBuildWrite.

**Comment by jrburke** [comment]
Looking more at this, and #788, it sounds like the main desire is "better source map support for things that include loader plugins".

The reason that is difficult right now is that build.flattenModule adds extra lines between file outputs, and does not give enough context into know what line numbers are in play for each segment in the onBuildWrite/onLayerEnd hooks.

I have been meaning to provide some lower level tools, likie "just trace and give all dependencies", and it sounds like if there was another one that just returned a structure that contained the module ID, file name (if applicable) and content for that ID for all items in a layer, then you could build a tool on top that creates the final output file and any source map.

So I will repurpose this ticket to track that request, although it may end up as a separate standalone tool. Also not likely to shoehorn it in with the 2.1 releases.
