### ISSUE TITLE
Why do empty module definitions get created?

### ISSUE THREAD

**Issue by sholladay** [requirejs/r.js#852]
Given a build configuration with:

``` js
modules : [
    {
        name : 'foo',
        create : true,
        include : [
            'bar'
        ]
    }
];
```

... the optimizer creates a file containing all of the code I expect. But in addition, it inserts:

``` js
define("foo", function(){});
```

... which seems completely useless to me. But it must have some purpose. Presumably this has something to do with using `create: true`, but I haven't found any other way to customize the final filename in `modules` mode.

When I was doing a "single page" build using `name` instead of `modules`, I was able to use the `skipModuleInsertion` option to prevent this (and I could also specify the output filename without `create`). But that doesn't seem to work for "multi-page" builds.

Before doing some hacky and slow regex replacement in my build system to avoid the extra download bytes, I figured I should ask about the dark magic here. Is there a good reason to let these empty module definitions stay?

**Comment by rjgotten** [comment]
>Is there a good reason to let these empty module definitions stay?

They're needed if you use `enforceDefine:true`.
In turn, `enforceDefine:true` is needed if you want error-handling and `path` configuration fallback handling to operate reliably in Internet Explorer.

**Comment by sholladay** [comment]
Thanks! As far as I can tell at a glance, `enforceDefine` would only need this behavior if my `include` directive didn't grab any files that call `define()`.
```
If set to true, an error will be thrown if a script loads that does not call define()
```
Since, I am always calling `define()` at least once in my optimized files, it seems like this is unnecessary. Or is it that `enforceDefine` demands a `define()` call for a module name that matches the file name it was loaded from? That would make some sense. So, is this just laziness, so to speak, in not checking whether `define()` calls were made in the file before it is written to disk?

Also, since I don't think I'll ever need to use `enforceDefine`, is there a good reason that `skipModuleInsertion` doesn't work for "multi-page" builds or is it just not currently implemented?

**Comment by rjgotten** [comment]
> Or is it that enforceDefine demands a define() call for a module name that matches the file name it was loaded from?

It's that one. It needs to be that one.
Because: loader plugins.

**Comment by sholladay** [comment]
Alright, fair enough. Thanks for the insight. I could really use something akin to `skipModuleInsertion`, though. hmm

**Comment by rjgotten** [comment]
> Also, since I don't think I'll ever need to use `enforceDefine`, is there a good reason that `skipModuleInsertion` doesn't work for "multi-page" builds or is it just not currently implemented?

`skipModuleInsertion` works fine in multi-page builds. It's just not honored when `create:true` is specified. ;-)

**Comment by sholladay** [comment]
I suppose I could commit a fake module named `foo` (see OP) to my source folder, in order to avoid using `create`. But that just seems like a hacky workaround for an optimizer deficiency.

**Comment by alexindigo** [comment]
Can you just add empty path?

```
paths: {
  "foo": "empty:"
}
```

– solves many problems :)

**Comment by sholladay** [comment]
I would consider that a reasonable solution if it was only `foo` or a couple others I had to worry about. Unfortunately, we are talking about >10 bundles that need to be created. It's going to get a bit unwieldy.

Semantically, what I want to tell the optimizer is not very complicated. I wish to compose some modules (`include`) to make a bundle. On the client, the loader will know how to get ahold of the bundle and the modules it contains because it'll have the [bundles config](http://requirejs.org/docs/api.html#config-bundles) that my build system computed because the optimizer [can't do this yet](https://github.com/jrburke/r.js/issues/613). The fact that `foo` doesn't exist in my source directory is just a side-effect of the fact that I'm making a bundle (no main entry point). I _could_ maybe extract the first `include` file and list it in `name`, but then the bundle would have a strange name. Plus, can the `bundles` config even handle a bundle named the same as a module it contains? That seems wrong.
