### ISSUE TITLE
 ReferenceError: "Float32Array" is not defined.

### ISSUE THREAD

**Issue by chaotive** [requirejs/r.js#894]
When trying to use three.js library on a few tests from my SBT project, I get the following error:

[info] running jasmine 1.3.1...
See https://github.com/jrburke/r.js for usage.
[  Envjs/1.6 (Rhino; U; Windows 7 amd64 6.1; en-US; rv:1.7.0.rc2) Resig/20070309 PilotFish/1.2.13  ]
Could not read file: D:\Proyectos\WebReleased\Active\source\units\partquest\libraries\pq-lib-3d-models\src\test\js\3rdlib\three\three-72.min.js
 error was: ReferenceError: "Float32Array" is not defined.

There are more errors following this one, but this seems to be the most important one and the following ones are probably created by this.

Any ideas? Thanks

**Comment by jrburke** [comment]
It is hard to know without more details on the project, ideally a test case. Possibilities might be if three.js is used as a dependency for a loader plugin, then it likely will not work in Rhino. loader plugins and their dependencies are evaluated in their full source form, so if Rhino does not define `Float32Array` then it likely will fail.

Closing as a discussion ticket, feel free to continue discussion here. If more details or a test case can be shared that uncovers a bug then we can reopen. Although this sounds like a problem with something trying to run three.js in Rhino, which likely will not work given how old Rhino is.
