### ISSUE TITLE
Single file optimizer excluding to much

### ISSUE THREAD

**Issue by chaosClown** [requirejs/r.js#895]
I am trying to combine files into bundles with the optimizer. The build itself works as expected, but when excluding `app` all depandencies of the second optimizer call get lost.

Here is my code:

**./build.js**

```
var requirejs = require('requirejs');

requirejs.optimize({
    baseUrl : './',
    out : './dist/js/common.js',
    mainConfigFile : [
        'config/common.js'
    ],
    optimize: 'none',
    name : 'app',
    paths : {
        requireLib : 'node_modules/requirejs/require'
    },
    include : [
        'requireLib',
        'config/common'
    ]
}, console.log);

requirejs.optimize({
    baseUrl : './',
    out : './dist/js/guest.js',
    name : 'guest',
    optimize: 'none',
    mainConfigFile : [
        'config/common.js',
        'config/guest.js'
    ],
    exclude : ['app'] //<-- toggle this line
}, console.log);
```

**./config/common.js**

```
requirejs.config({
    baseUrl : './',
    packages : [
        'app',
        'guest'
    ],
    bundles : {
        'js/guest' : ['guest']
    }
});
```

**./config/guest**

```
requirejs.config({
    packages : [
        'guest/something'
    ],
    deps : [
        'guest/something'
    ]
});
```

**./app/main**
```

define(function() {
    function App() {
        //..
    }

    App.prototype = {
        //...
    };

    return App;
});
```

**./guest/main**

```
define(['app'], function(App) {
    function Guest() {
        //..
    }

    Guest.prototype = Object.create(App, {
        constructor : {
            value : Guest
        }
        //...
    })

    return Guest;
});
```

**./guest/something/main**
```

define(function() {
    return function() {
        //do something
    }
});
```

**output without exclude : 'app'**

```
~/test/dist/js/common.js
----------------
~/test/node_modules/requirejs/require.js
~/test/app/main.js


~/test/dist/js/guest.js
----------------
~/test/guest/dosomething/main.js
~/test/app/main.js
~/test/guest/main.js
```

**output with exclude : 'app'**

```
~/test/dist/js/common.js
----------------
~/test/node_modules/requirejs/require.js
~/test/app/main.js


~/test/dist/js/guest.js
----------------
~/test/guest/main.js
```

**r.js -v**

`r.js: 2.1.22, RequireJS: 2.1.22, UglifyJS2: 2.6.1, UglifyJS: 1.3.4`

The dependency `guest/something` will get excluded. This seams strange to me, as `app` doesn't require anything.

Am I missing something, how to come around it?

**UPDATE**

After some investigation it turned out that the deps properties creates the problem. It seams only to work without exclude. Using include instead works but the config can't be shared so smooth.

**UPDATE 2**

for everybody who has the same problem, here is what i did to get the data out of the config file, you may adjust the path to you needs.

```
function getConfig(id) {
    var cfg;

    var sandbox = new vm.createContext({
        requirejs : {
            config : function(localCfg) {
                cfg = localCfg;
            }
        }
    });

    var script = new vm.Script(fs.readFileSync(id+'.js'));
    script.runInContext(sandbox);
    return cfg;
}

var configCommon = getConfig('config/common');

```

**Comment by jrburke** [comment]
Looks like the root issue was found. If you wanted to do a more custom bundling or exclusion of modules, you might try [amodro-trace](https://github.com/amodrojs/amodro-trace), which just does a trace and leaves it up to your code to program the resulting bundles.
