### ISSUE TITLE
Understanding relative paths with a very simple "hello world" like example

### ISSUE THREAD

**Issue by greggman** [requirejs/r.js#897]
I'm sorry to ask what's probably been asking 100+ times. But.... I made what I think is the smallest possible example. I'm not really understanding what I'm doing wrong.

I'm using [almond](https://github.com/jrburke/almond/). I've tried a bunch of stuff

Here's my layout

    .
    ├── 3rdparty
    │   ├── require.js   // here for browser testing
    ├── src
    │   ├── lib.js
    │   └── main.js
    └── node_modules
        ├── requirejs
        │   └── ...
        └── almond
            └── almond.js

And here's my build.js

```
   ({
     baseUrl: "./",
     name: "node_modules/almond/almond.js",
     include: [ "src/main.js" ],
     out: "dist/r-app.js",
     optimize: "none",
   })
```

main.js looks like this

    requirejs(['./lib',], function(lib) {
      lib.hello();
    });

lib.js looks like this

    define([], function() {
        return {
          hello: function() {
              console.log("hello from lib");
          },
        };
    });

If run a web page that uses require.js as in

    <script src="3rdparty/require.js" data-main="src/main.js"></script>

It runs great. [You can see it live it here](http://greggman.github.io/grunt-contrib-requirejs-example/test-before.html). Check the console and you'll see it prints `hello from lib`

So I run r. 

    ./node_modules/requirejs/bin/r.js -o build.js

Then I run `r.app` in node (`node dist/r-app.js`) and I get the error

    Uncaught Error: undefined missing lib

Checking the generated `dist/r-app.js` I see lib has been turned into this

    define('src/lib',[], function() {
       ...
    });

And main is including it like this

    requirejs(['./lib'], function(lib) {
      ...
    });

In other words, the id that r.js generated `src/lib` doesn't match the id that main is referencing `./lib`.

This seems like a very straight forward example for r.js. Like practically "hello world".

What am I doing wrong?

One thing I've tried is changing the `baseUrl` to `./src`

```
({
  baseUrl: "./src",
  name: "node_modules/almond/almond.js",
  include: [ 'main.js' ],
  out: "dist/r-app.js",
  optimize: "none",
})
```

But now I get 

```
Tracing dependencies for: node_modules/almond/almond.js
Error: Error: ENOENT: no such file or directory, open '/Users/gregg/temp/grunt-contrib-requirejs-example/src/node_modules/almond/almond.js'
    at Error (native)
```

So I try fixing the almond path

```
({
  baseUrl: "./src",
  name: "../node_modules/almond/almond.js",
  include: [ 'main.js'],
  out: "dist/r-app.js",
  optimize: "none",
})
```

But that fails as well

```
/r-script 
Error: Error: ERROR: module path does not exist: ../node_modules/almond/almond.js for module named: ../node_modules/almond/almond.js. Path is relative to: /Users/gregg/temp/grunt-contrib-requirejs-example
    at /Users/gregg/temp/grunt-contrib-requirejs-example/node_modules/requirejs/bin/r.js:30214:35
```

Which seems like there's some issue where r is looking for for almond once without baseUrl and again with baseUrl

What am I not getting?

[The entire thing is checked into github here](https://github.com/greggman/grunt-contrib-requirejs-example) if you'd like to work with it. It's mixed in with grunt example but basically

    git clone https://github.com/greggman/grunt-contrib-requirejs-example.git
    cd grunt-contrib-requirejs-example
    npm install 
    ./r-script

will run r and generate dist/r-app.js

Thank you for any insight you can provide

**Comment by jrburke** [comment]
The issue is that r.js likes to work with module IDs, and not paths, for `name` and `include`. `out` is a file path though, since that deals with the output, where to place the generated bundle.

I did this diff to get it to work:

```patch
diff --git a/build.js b/build.js
index b1c4e06..b0ce016 100644
--- a/build.js
+++ b/build.js
@@ -1,8 +1,11 @@
 ({
-  baseUrl: "./",
-  name: "node_modules/almond/almond.js",
-  include: [ 'src/main.js'],
-  out: "dist/r-app.js",
+  baseUrl: "./src",
+  paths: {
+    almond: '../node_modules/almond/almond'
+  },
+  name: "almond",
+  include: [ 'main.js'],
+  out: "dist/app.js",
   optimize: "none",
 })
```
