### ISSUE TITLE
Outputting a filename different from the module name when using "modules"?

### ISSUE THREAD

**Issue by lostthetrail** [requirejs/r.js#899]
```
//A simple build file using the tests directory for requirejs
{
    baseUrl: "../../../requirejs/tests/text",
    paths: {
        text: "../../../requirejs/../text/text"
    },
    dir: "builds/textExclude",
    optimize: "uglify",
    modules: [
        {
            name: "widget",
            exclude: ['text!subwidget2.html'],
            out: "build/widget.min.js"
        }
    ]
}
```

I also tried overrides.out, but it didn't do anything else.

Any suggestions?

**Comment by jrburke** [comment]
If you are just doing a [single file optimization](http://requirejs.org/docs/optimization.html#onejs), then skip the `modules` use, and instead use `out`:

```javascript
{
    baseUrl: "../../../requirejs/tests/text",
    paths: {
        text: "../../../requirejs/../text/text"
    },
    dir: "builds/textExclude",
    optimize: "uglify",
    name: "widget",
    exclude: ['text!subwidget2.html'],
    out: "build/widget.min.js"
}
```

The `modules` and `dir` use is for [whole project](http://requirejs.org/docs/optimization.html#wholeproject) optimizations, where the goal is to keep the `dir` output similar to the source output.

If you want more control about how things are grouped and saved, I suggest using [amodro-trace](https://github.com/amodrojs/amodro-trace) which gives a basic API for tracing modules.

Closing as a discussion ticket, feel free to continue discussion here.
