### ISSUE TITLE
Removing duplicated @charset directive from imported css file contents.

### ISSUE THREAD

**Issue by FuweiChin** [requirejs/r.js#902]
There are 3 css files:
form.css
```css
@charset "UTF-8";
.form{
}
```
table.css
```css
@charset "UTF-8";
.table{
}
```
page1.css
```css
@charset "UTF-8";
@import url("form.css");
@import url("table.css");
```
When I optimized page1.css to page1-combined.css, there exists multiple @charset directives.
page1-combined.css
```css
@charset "UTF-8";
@charset "UTF-8";
.form{
}
@charset "UTF-8";
.table{
}
```
the `page1-combined.css` is expected to be:
```css
@charset "UTF-8";
.form{
}
.table{
}
```

**Comment by jrburke** [comment]
The CSS bundling is very simplistic. It has some other issues besides this one, and in retrospect I should have separated it out as its own tool. I do not have any plans to improve the CSS bundling behavior, and at this point there are likely better packages you could use for those needs, particularly if you are using nodejs to run the builds. I suggest trying other tools if you want better bundling behavior for CSS.

So closing as I am not likely to fix it, but I recognize that this CSS output is not desirable.
