### ISSUE TITLE
Deps in config.shim aren't included

### ISSUE THREAD

**Issue by JoniJnm** [requirejs/r.js#904]
The dependences in config.shim aren't included in r.js

An example:

* js/a.js
* js/b.js
* js/main.js
* config.js

a.js

```js
define(function(require, exports, module) {
  exports.a = a;
});
```

b.js

```js
define(function(require, exports, module) {
  exports.b = 'b';
});
```

main.js

```js
require(['b'], function(b) {
  console.log(b.b);
});
```
config.js

```js
requirejs.config({
  baseUrl: 'js',
  shim: {
    'b': {
      deps: ['a']
    }
  }
});
```

The output, built.js
```js
define('a',['require','exports','module'],function(require, exports, module) {
  exports.a = a;
});

define('b',['require','exports','module'],function(require, exports, module) {
  exports.b = 'b';
});

require(['b'], function(b) {
  console.log(b.b);
});

define("main.js", function(){});
```

The define of "b" should be:

```js
define('b',['require','exports','module', 'a'],function(require, exports, module) {
  exports.b = 'b';
});
```

because "b" needs "a".

requirejs isn't loading 'a' when someone needs 'b' because b is already defined. So, maybe r.js is OK, but requirejs has to load 'a' when someone needs 'b', even if b is already defined.

**Comment by jrburke** [comment]
Shim config is only for modules that do not call the define() module API themselves. More detail is in the notes section of the [shim config doc section](http://requirejs.org/docs/api.html#config-shim). Mixing shim with a module with define() will have unpredictable effects.

Closing as a discussion ticket.

**Comment by JoniJnm** [comment]
Thanks for the response.

I have read the shim config doc section, but I don't know what's wrong in my code.

I created in github a very example project where the problem occurs. It's works ok in "normal mode", but the optimized version doesn't work.

I'm passing the shim config to r.js.

If you want, you can see the repo and... tell me what I'm missing.

https://github.com/JoniJnm/requirejs-904

Thanks!

**Comment by jrburke** [comment]
Since mymodulea.js uses define(), then the shim config will not be applied after a build. Before a build, since mymodulea was not registered via define() yet, since the loader has no info on mymodulea, it will use the shim config. However after a build, those define calls have run before the require([]) to trigger module executions has begun, so since the loader has a module API call that informs it of the module, shim config is not used.

shim config is for scripts that do not use define(), not module aware.

If modulea really depends on moduleb, then modulea should use `require('moduleb')` inside of itself to indicate that dependency.

**Comment by JoniJnm** [comment]
I don't why r.js can't simply concat the deps from config.shim to the define(), something like:

```js
var shim = config.shim[moduleName];
if (shim) {
    //concat shim dependeces
    var deps = lang.isArray(shim) ? shim : (shim.deps || []);
    moduleDeps = moduleDeps.concat(deps);
}
depString = arrayToString(moduleDeps);
result += 'define("' + moduleName + '",' + depString + ');';
```

So, the define() will have mymoduleb, and it will be loaded.

 But... it's OK! Thank you very much for the response.
