### ISSUE TITLE
r.js not overwrite waitSeconds

### ISSUE THREAD

**Issue by re2005** [requirejs/r.js#905]
If you use r.js with the build.js example:
https://github.com/requirejs/r.js/blob/master/build/example.build.js

The default "waitSeconds" property won't have the  value modified in the new bundle created.

Any idea if this is a bug or wrong usage of the param waitSeconds

Thanks

**Comment by jrburke** [comment]
The config passed to r.js is just used to drive the r.js optimizer for module tracing. It does not modify the output text of a bundle to include the build config.

If you want to modify the waitSeconds as part of the build, you can use the [onBuildWrite](http://www.ericfeminella.com/blog/2012/03/24/preprocessing-modules-with-requirejs-optimizer/) hook in the build config to do a regexp replacement of the value.

Closing as a discussion ticket, feel free to continue discussion here.

**Comment by re2005** [comment]
**Thanks to reply me James!**

I'm using RequireJS to load a page in a slow connection and what i've noticed is the "waitSeconds" 7 seconds is something "not easy" to overwrite on the default setup.

Im running the example page from Git:
https://github.com/requirejs/example-multipage-shim

<img width="1787" alt="screen shot 2016-03-27 at 18 43 36" src="https://cloud.githubusercontent.com/assets/2920357/14066533/2f8203f0-f44c-11e5-8664-2855e1ad8d06.png">

You see the problem:
Uncaught Error: Load timeout for modules: js/common

I know oder ways to solve it but for me overwriting the default value is a ideal solution.

What you recommend in this case?
Thanks in advance!

**Comment by re2005** [comment]
For the ones who need the same solution:

`onBuildWrite : function( name, path, contents ) {
        if (name == 'js/lib/require') {
            var match = 'waitSeconds: 7';
            var replaceMatch = 'waitSeconds: 0';
            contents = contents.replace(match, replaceMatch);
        }
        return contents;
    }
`

Thanks!
