### ISSUE TITLE
Callback has no response when using the optimizer as a node module

### ISSUE THREAD

**Issue by iooly** [requirejs/r.js#906]
I use the optimizer as a node module, but the callback has no response. The code is:

```
var requirejs = require('requirejs');
var fs = require('fs');

var config = {
        logLevel:0,
        baseUrl: '../appDir/scripts',
        name: 'main',
        out: '../build/main-built.js'
};

requirejs.optimize(config, function (buildResponse) {
        //buildResponse is just a text output of the modules
        //included. Load the built file for the contents.
        //Use config.out to get the optimized file contents.
        var contents = fs.readFileSync(config.out, 'utf8');
        console.log(contents);
}, function(err) {
        //optimization err callback
        console.log(contents);
});

```
The two callbacks (callback and errback)  totally has no response. My node version is 4.2.1 and os is KDE 15.0.4

**Comment by jrburke** [comment]
The basic mechanism is [tested in the unit tests](https://github.com/requirejs/r.js/blob/master/build/tests/nodeOptimize.js), so something unusual must be occurring. Just tried that test again now, on node 4.4.2, requirejs 2.2.0, but on OS X, and it works. I would not expect the OS type to matter in this case.

If you use a node debugger and set breakpoints in the callback and errback, do those work? Or, maybe the callback is working, but the fs.readFileSync fails and that error is getting lost?

To debug more, a test case that I can run would likely be needed.

**Comment by iooly** [comment]
I'm sorry but I copied an example from network and I had response and worked well. Maybe there is something wrong in my code.

**Comment by jrburke** [comment]
Feel free to reference a test case then and we can reopen as needed. If one of the callbacks is not called, then still seems like a weakness in r.js, letting something drop.
