### ISSUE TITLE
"-" in module name causes problems

### ISSUE THREAD

**Issue by RafaelSalguero** [requirejs/r.js#910]
When using the module `angular-ui-router` with the following path and shim:
```js
//path:
'angular-ui-router': "./node_modules/angular-ui-router/release/angular-ui-router",

//shim:
 'angular-ui-router': { exports: 'angular-ui-router', deps: ['angular'] },
```

r.js generates this code at the end of the angular-ui-router module:
```js
define("angular-ui-router", ["angular"], function(global) {
    return function() {
        var ret;
        //Note that the "-" in this context is a minus sign and not part of the module name
        return ret || global.angular - ui - router
    }
```

Which causes the error "ui is not defined" 

Maybe the correctly generated code would be

```js
define("angular-uiRouter", ["angular"], function(global) {
    return function() {
        var ret;
        //Note that the "-" in this context is a minus sign and not part of the module name
        return ret || global.["angular-ui-router"]
    }
```
?

The workaround is to rename the module without "-" signs such as `angularUiRouter`

Strangely I have another module named `ui-boostrap` which didn't present this problems

**Comment by jrburke** [comment]
Does the angular-ui-router file actually export a global called "angular-ui-router"? That seems like bad practice, it does not work as a regular JavaScript identifier and would require that ['angular-ui-router'] to use. I can't see that export when looking at the file.

Looks like you might want to use something more like "angular.ui.router" as the exports string, but I'm not too familiar with angular.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by RafaelSalguero** [comment]
You are right the exported module name from that library is "ui.router". Thanks
