### ISSUE TITLE
bundlesconfigoutfile - no such file or directory

### ISSUE THREAD

**Issue by pavkum** [requirejs/r.js#911]
Hello,
  This may not be an issue, but I couldn't get much information regarding **bundles config** outside. So directly requesting for help here.

  We are trying to do whole project optimizations and so far we have few modules defined. So far everything looks fine.  We have couple of libraries, helpers which are common across multiple modules. So we thought of using bundles to list and load them. 
   
  Now I wanted to automatically trace these dependencies across multiple modules and wanted to export them as config using **bundlesconfigoutfile** property (Is my assumption correct here?).

  But when I set up the property during r.js optimization I get error saying no such file or directory for the outFile which I have specified for **bundlesconfigoutfile** property while tracing dependencies(this file generates automatically right?).  What am I doing wrong?

 Please find my requirejs config below
`
    
    {
       "appDir": "courses",
       "baseUrl": ".",
       "dir": "build_courses",
       "optimize": "none",
        "shim": {
           "jquery": {
           "exports": "jQuery"
         },
        "underscore": {
           "exports": "_"
        },
        "ember": {
           "deps": [
              "jquery"
           ],
           "exports": "Ember"
        }
      },
      "paths": {
      "jquery": "../lib/jquery/jquery",
       "underscore": "../lib/underscore/underscore",
       "ember": "../lib/ember/ember.debug",
      },

      "modules": [{
          name: "courses/index",
          excludes: [
            'jquery',
            'ember',
         ]
      }, {
        name: "dummy",
        create: true,
        include: [
           "courses/routes/coursesRoute"
        ]
      }],
      "bundlesConfigOutFile": "../bundles.config.js"
     }`

In my set up, courses/index module has reference to courses/routes/coursesRoute. My dummy module references the same. I thought **bundlesconfigoutfile** will extract out this common dependency. Am I correct here?

**Comment by jrburke** [comment]
bundlesConfigOutFile needs to target the js file that has your primary requirejs.config() call so that it can inject the bundle config into that config call. This makes sure the config will be registered before the rest of module loading occurs. So, it is not designed to be used to output to a new file.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by pavkum** [comment]
@jrburke Thanks for the clarification. I got it working

**Comment by johnib** [comment]
I couldn't get it working.
It did not add any _bundle_ property to the require.config.js of the output.

I did test it on a single bundle though... but the requirejs config does apply to the "optimizing whole project" specifications.

What else could I missed?

**Comment by pavkum** [comment]
@johnib bundles is valid only for whole project optimization.

**Comment by johnib** [comment]
I'm optimizing the whole project.

**Comment by pavkum** [comment]
Could you please reply with your config file and bundles.configout file. I
will correlate with mine.

Also bundles.configout file contents should be wrapped between
requirejs.config().
