### ISSUE TITLE
Fine Grained API

### ISSUE THREAD

**Issue by EisenbergEffect** [requirejs/r.js#913]
I see that there's an `optimize` API. Are there any other public APIs that are more fine-grained? For example, could I feed a source file in and do any of the following:

* Detect the module type?
* Convert a CommonJS module to AMD?
* Convert an anonymous AMD module to a named module?
* Get the dependencies of an AMD/CommonJS module?
* Wrap a "global" module?

I'm thinking of building a custom build/bundle process. I'm skeptical that we can do it with the course grain `optimize` API but I was wondering if there were public utility methods (possibly documented somewhere) that I could use to put together a custom process. It seem that all this has to be in r.js somewhere, so I'd hate to have to re-implement it all.

Thanks!

**Comment by EisenbergEffect** [comment]
Perhaps this is what I'm looking for? https://github.com/amodrojs/amodro-trace

**Comment by jrburke** [comment]
Yes, I recommend starting with amodro-trace. It is kept up to date with requirejs releases, and what I suggest to people that want fine grained control over the bundling process.

Closing as a discussion to ticket, feel free to continue discussion here.
