### ISSUE TITLE
pre-compile package only?

### ISSUE THREAD

**Issue by gbaumgart** [requirejs/r.js#914]
Hi,
I am having a hard time to pre-compile a package with r.js (via grunt-contrib-requirejs).

The problem is that the package uses other modules from packages as well and so r.js adds these modules in the output too. To solve that, I found currently only the exclude option but it doesn't support wildcards and so I'd have to know every module to be excluded (hundreds!) and put them in the option (nogo)

The other option was to limit baseUrl to the package only but then the build aborts because it can't find the dependencies.

Any ideas? 

Ah, at the end I want to load the "pre-compiled" version of a package or the full package source tree in my application.

**Comment by ScottFreeCode** [comment]
Let me know if you come up with a solution for this; I'm curious to know if it can be done.

**Comment by jrburke** [comment]
[amodro-trace](https://github.com/amodrojs/amodro-trace) might be an option if you want finer grained control over the bundling process.

**Comment by gbaumgart** [comment]
at the end i just made the grunt task perfect for the layers; i can even just use my dojo-package/main.js as main build entry and in seconds its ready. works fantastic, not knowing yet what the compiler does (love gcc)
