### ISSUE TITLE
is it support text template?

### ISSUE THREAD

**Issue by zzzgit** [requirejs/r.js#917]
the js part of `index.html`:
```
require("text!car.tmpl",function(car){
     // do something
});
```
if i use `r.js` to optimize this js file,could it integrate the template file into the html file?

**Comment by jrburke** [comment]
If the JS file contains:

```javascript
require(["text!car.tmpl"],function(car){
     // do something
});
```

And that file is given to the r.js file via a build config, then as long at the text.js plugin file is also in the project/found with the r.js config, then the resulting built JS file will look something like this:

```javascript
define("text", [], function() {
  // defines the "text" module.
});

define("text!car.tmpl", [], function() {
  return 'contents of car.tmpl';
});

require(["text!car.tmpl"],function(car){
     // do something
});
```

And if that built JS file is loaded by require.js, then it will not need to dynamically load the template.

It will not inject this JS into an HTML file though, if that was the question.

Closing as a discussion ticket, but feel free to continue discussion here.
