### ISSUE TITLE
delete source 

### ISSUE THREAD

**Issue by lihua123569** [requirejs/r.js#918]
Compression is completed, the direct use of compressed files to replace the original file, this value appears to be not available! Is there any way to achieve? No parameter support?

**Comment by jrburke** [comment]
There is the [removeCombined option](https://github.com/requirejs/r.js/blob/master/build/example.build.js#L343) for [whole project optimizations](http://requirejs.org/docs/optimization.html#wholeproject), but that is the extent of that kind of removal capability.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by lihua123569** [comment]
First of all, thank you,but you may not understand my problem.please look at the following diagram
![Uploading V4_C2S8S_R6GT3N]FC@MFWJ.png…]()
The above Inc is my source file, the following scripts is my compressed storage of the file position, I want to use the following Inc inside the scripts to replace the above Inc

**Comment by gsmeets** [comment]
I would *strongly* recommend to never do this. You'll regret it that time when you run your grunt/gulp build command on code that hasn't been checked in yet, and suddenly you've uglified your code, or worse...

The best solution is to copy it to another directory, and do the swap out of the combined files for the original files as late as possible in your deploy pipeline.

**Comment by lihua123569** [comment]
I know that when I deploy the project, I use jekins to deploy, pull from the SVN code, to distinguish the environment packaged. Will not pollute my SVN code, if you can achieve the best, then I can only distinguish between environmental treatment
