### ISSUE TITLE
Optimizer "tracing dependencies" multiple times for across the modules

### ISSUE THREAD

**Issue by tHBp** [requirejs/r.js#920]
I have a large project with my config file spanning over 200+ modules and all modules have some common elements in exclude list.
They all get traced again and again, for each module, causing the optimizer to take more than 2-3 mins, which personally I feel should be over in about 20-30 seconds.

**EDIT**
@jrburke Similar issue was discussed in issue #6 and marked closed.
Still I seem to encounter the same.

**Comment by tHBp** [comment]
Here is a sample test case to reproduce the problem.

Here is the directory structure

![image](https://cloud.githubusercontent.com/assets/16330770/16414738/0e7b6d00-3d57-11e6-8dce-1e552a72ed99.png)

Here are the files,

**test-script.js**
```javascript```
var requirejs = require('requirejs');
var config = {
    baseUrl : 'src/',
    optimize: 'none',
    dir: './dist',
    logLevel:0,
    paths: {
        'jquery': '../libs/jquery'
    },
    modules: [{
        name: 'shortName',
        exclude: ['jquery']
    }, {
        name: 'some-file-name/random-file-name',
        exclude: ['jquery']
    }]
};

requirejs.optimize(config, function(buildResponse) {
    console.log("optimization done");
}, function(err) {
    console.log(err);
    console.log("optimization failed");
    throw err;
});
```
**short-name.js**
```javascript```
define([
    'jquery',
    './dependency'
], function() {
    return "x";
});
```
**dependency.js**
```javascript```
define([
    'jquery'
], function() {
    return "z";
});
```
**random-file-name.js**
```javascript```
define([
    'jquery',
    '../dependency'
], function() {
    return "y";
});
```
The output is:

![image](https://cloud.githubusercontent.com/assets/16330770/16414904/18cf1008-3d58-11e6-9012-7f5f681de889.png)

Now this here is a small test case, in which _jquery_ is repeated twice. Now as it happens, I have over 200+ modules, so the exclude list having almost same list of dependencies is traced again per module.

**Comment by tHBp** [comment]
I have run into a new trouble. The optimization now runs out of memory. (Javascript heap out of memory). This might be the direct effect of tracing dependencies again and again. Although, I can workaround by increasing --max_old_space_size for now, but it might be worth looking into.

**Comment by jrburke** [comment]
If you create a named build layer that matches the exclude name, then I believe the build should use that cached build layer result for the later exclude uses, and not retrace. Note that those layers need to be defined before the exclude usage to work:

```javascript
var config = {
    baseUrl : 'src/',
    optimize: 'none',
    dir: './dist',
    logLevel:0,
    paths: {
        'jquery': '../libs/jquery'
    },
    modules: [{
        // This is the new thing added to the build config
        name: 'jquery'
    }, {
        name: 'shortName',
        exclude: ['jquery']
    }, {
        name: 'some-file-name/random-file-name',
        exclude: ['jquery']
    }]
};
```

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by tHBp** [comment]
@jrburke Your suggestion worked great. Thanks a lot.
However, I was thinking maybe we should cache the exclude listed libraries' dependencies too.
That way, we won't have to explicitly define them as modules.

**Comment by jrburke** [comment]
That sort of caching would be a larger change to r.js, I am now at the point of pointing people that want more control over the parsing/caching to build their own imperative solutions using [amodro-trace](https://github.com/amodrojs/amodro-trace).
