### ISSUE TITLE
Syntax error in addFile uglify.js using sctrict mode

### ISSUE THREAD

**Issue by Harsgalt** [requirejs/r.js#928]
During build, following error occurs

/node_modules/grunt-durandal/node_modules/requirejs/bin/r.js:22358
        function addFile(file, fileUrl) {
        ^^^^^^^^
Loading "build-durandal.js" tasks...ERROR
>> SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.

Broken by commit https://github.com/requirejs/r.js/commit/90f19653c5449df5fe8bd683cae4358bc8dfcf90

**Comment by M3kH** [comment]
I'm getting the same error.
This is also related to #1583

**Comment by jackw** [comment]
I'm also hitting this. I've forced npm to install 2.2.0 for the time being. @janza thanks for fixing so quickly.

**Comment by jrburke** [comment]
Going to use #929 to track fixing the issue. I'll add more details and expand on a fix there.
