### ISSUE TITLE
Problem in getting started with RHMAP

### ISSUE THREAD

**Issue by ujjaineesarkar** [requirejs/r.js#932]
I'm facing this error whenever I'm going to set the path for getting the targets.
C:\Users\986216\AppData\Roaming\npm\node_modules\fh-fhc\bin\fhc.js
line :1
Char:1
Error:Invalid character
Code:800A03F6
Source:Microsoft Jscript compilation error

Then I saw in git that fhc.js.cmd will work.
C:\Users\986216\AppData\Roaming\npm\node_modules\fh-fhc\bin>cd fhc.js.cmd
The system cannot find the path specified.
So what should I do?

**Comment by jrburke** [comment]
I think this was not posted to the correct project. RHMAP and fhc are not things associated with running the code in this repo.

Closing as a discussion ticket, but feel free to continue discussion here.
