### ISSUE TITLE
CSS is not excluded as expected

### ISSUE THREAD

**Issue by StefanJelner** [requirejs/r.js#938]
hello,

first of all thanks for this great piece of code. it is saving us lots of headaches in our build processes.

i have a little problem with r.js, not excluding CSS-files, even they are explicitely excluded in the modules-list.

here is my project structure:

    src
      dependencies
        css.js
        jquery.js
        jquery-ui.js
        require.js
        ...
      lib
        iconhandler.js
        templatengine.js
        trick-o-matic.js
        ...
      plugins
  	  colorchooser
  	    farbtastic
  		  farbtastic.css
  		  farbtastic.js
  		  ...
  		structure_plugin.js
  		...
      index.html
  	...
    build.js
    package.json
    ...

in `src/index.html` i have the following line:

    <script data-main="lib/templateengine" src="dependencies/require.js" type="text/javascript"></script>

the `src/plugins/colorchooser/structure_plugin.js` looks like this:

    define( ['structure_custom', 'css!plugins/colorchooser/farbtastic/farbtastic.css', 'plugins/colorchooser/farbtastic/farbtastic' ], /* code */ );
  
the `build.js` looks like this:

    ({
      baseUrl: './',
      appDir: 'src/',
      dir: 'release/',
      mainConfigFile: 'src/lib/templateengine.js',
      separateCSS: true,
      buildCSS: false,
      paths: {
        'css-builder': '../node_modules/css-builder/index',
        'normalize': '../node_modules/normalize/lib/normalize'
      },
      preserveLicenseComments: false,
      modules: [
        { name: 'lib/templateengine', include: ['css'] },
        { name: 'plugins/colorchooser/structure_plugin', exclude: ['structure_custom', 'css', 'normalize']  }
      ]
    })

when i run the build process, i get the following errors:

    Tracing dependencies for: plugins/colorchooser/structure_plugin
    TypeError: Cannot set property 'exports' of undefined
    In module tree:
        plugins/colorchooser/structure_plugin
    
    Error: TypeError: Cannot set property 'exports' of undefined
    In module tree:
        plugins/colorchooser/structure_plugin
    
        at eval (eval at <anonymous> (r.js:25271:38), <anonymous>:18:16)

if i change the file `src/plugins/colorchooser/structure_plugin.js` to:

    define( ['structure_custom', 'plugins/colorchooser/farbtastic/farbtastic' ], /* code */ );

it works.

what am i doing wrong? can you help me?

thanks in advance,

Stefan Jelner

**Comment by jrburke** [comment]
It sounds like maybe the css plugin is not structured to work well in a build environment. Knowing which css! plugin might point to an answer. I am not so familiar with the different types of css plugins, may need to consult that plugin's repo or readme if it has specialized build advice. If there is a test repo that demonstrates the problem that also helps.

Closing as a discussion ticket, but feel free to continue discussion here, we can reopen if we find a code change that needs to be done.

**Comment by StefanJelner** [comment]
hello James Burke,

thank you for the quick answer.

the file `src/dependencies/css.js` is "Require-CSS RequireJS css! loader plugin 0.1.2".

thanks in advance,

Stefan Jelner

**Comment by StefanJelner** [comment]
fixed the problem myself.

the line `'css-builder': '../node_modules/css-builder/index',` had to be changed to `'css-builder': '../src/dependencies/css',`.

now it works.
