### ISSUE TITLE
r.js -o does not include dependencies

### ISSUE THREAD

**Issue by linvi** [requirejs/r.js#941]
I am trying to use `r.js -o` in order to build a single file containing the main module as well as all the dependent modules.

Here is my structure :

```
app 
    libs
        almond.js // https://raw.githubusercontent.com/requirejs/almond/latest/almond.js
    main.js
   depdency.js
build.js
```

Here are the files :

``` js
// app/main.js
var d = require('./dependency');
exports.module = d;

// app/dependency.js
module.exports = function() {
    return 'hello';
}
```

Here is the `build.js`

``` js
({
    baseUrl: 'app',

    out: 'build/main.js',
    optimize: 'none',

    name: 'main',
    include: ['libs/almond' ],
    wrap: false
})
```

When i run the command `r.js.cmd -o build.js` from the root folder, I have the following log :

``` text
Tracing dependencies for: main

root/build/main.js
----------------
root/app/libs/almond.js
root/app/main.js 
```

As you can see there is no reference to `dependency.js`. And actually `dependency.js` is not included in the output file.

``` js
// ... all the almond.js code is here

var d = require('./dependency');
exports.module = d;
define("main", function(){});
```

Am I doing something incorrect that result in `dependency.js` to not be part of the output file, or is there anything wrong with `r.js`?

NOTE : If I add the `dependency.js` to the `include` array, the build does work, but obviously I do not want to reference all files a module depends on for bigger projects.

Thanks

**Comment by jrburke** [comment]
The loader can only trace AMD modules by default, not CommonJS modules. So, modules wrapped in a `define` call. AMD versions of those modules:

```javascript
// app/main.js
define(function(require, exports, module) {
  var d = require('./dependency');
  exports.module = d;
});

// app/dependency.js
define(function(require, exports, module) {
  module.exports = function() {
      return 'hello';
  }
}):
```

The other option is to ask the optimizer to translate CommonJS modules to AMD modules by passing [cjsTranslate: true](https://github.com/requirejs/r.js/blob/aa349c72576dfb08ee14f599f77c2f8d63ec39e2/build/example.build.js#L581) in the optimizer build config.

Closing as a discussion ticket, but feel free to continue discussion here.
