### ISSUE TITLE
Update esprima and uglify if applicable

### ISSUE THREAD

**Issue by jrburke** [requirejs/r.js#942]
Esprima 3.1.0 is out now, get latest release before the r.js 2.3.3 release. Also look for any new uglify release.

**Comment by markerikson** [comment]
The current build of r.js (2.3.2) appears to use a much older version of Esprima (2.0).  Based on the Esprima changelog at https://github.com/jquery/esprima/blob/master/ChangeLog , that means it doesn't support the majority of ES6 features.

It would be _very_ helpful if r.js could use the latest Esprima and gain ES6 support.

I briefly tried cloning the r.js repo, overwriting esprima.js with the latest version, and rebuilding.  That produced a new r.js output file, but running it gave me an error:

```
Error: Tried loading "esprima" at ./esprima.js then tried node's require("././esprima") and it failed with error: Error: Cannot find module '././esprima'
```

Figured it wasn't worth me trying to pursue that further myself.  So, if you could update r.js to the latest esprima and cut a release, that would be greatly appreciated.  Thanks!

**Comment by jrburke** [comment]
I updated master to esprima 3.1.3, you can get the master snapshot here if you need something immediately:

https://raw.githubusercontent.com/requirejs/r.js/master/dist/r.js

I will try to wrap up the rest of the bugs in the 2.3.3 bucket to get a release out this weekend, but we will see how it goes.

**Comment by markerikson** [comment]
Great, thanks!  We'll give it a shot.

**Comment by jrburke** [comment]
Both esprima and uglify have been updated in master.

**Comment by jrburke** [comment]
2.3.3 has been released with this change.

**Comment by markerikson** [comment]
Good news is that the Esprima update appears to help.  Unfortunately, we're now seeing errors like this:

```
Uglify file:$PROJECT/icons/caret.js
Error: Cannot uglify file: $PROJECT/icons/caret.js. Skipping it. Error is:
SyntaxError: Name expected (line: 3, col: 14, pos: 69)
```

The relevant line of code is a "simple" const destructuring, roughly:  `const {a, b} = obj;`

Upon looking around, it appears that Uglify still does not support ES6 (per https://swizec.com/blog/fun-surprise-uglifyjs-cant-es6/swizec/7272 and https://github.com/mishoo/UglifyJS2/issues/448).

However, the Uglify issue points to https://www.npmjs.com/package/uglify-js-harmony , a fork which _does_ supposedly support ES6.

I was able to clone the r.js repo and follow the instructions for updating its Uglify version, but pointed to uglify-js-harmony instead, then rebuilt the r.js file.  That new custom build appears to correctly minify our ES6 code.
