### ISSUE TITLE
Improvement: Allow to skip certain files from minification/uglification but not from concatenation.

### ISSUE THREAD

**Issue by tavisca-akatte** [requirejs/r.js#945]
Add ability to skip certain files/folder to be skipped from minification but not from the concatenation.
I have situation where, I've added minified angularjs and r.js minifies it again. Due to double minification angular script is breaking.

**Comment by ScottFreeCode** [comment]
I would think that double-minification, while computationally redundant, shouldn't break anything...

**Comment by jrburke** [comment]
The suggestion is to run the minification as build step after r.js build process, and not minify in the r.js step. The number of options in the r.js config is pretty large now, and the JS ecosystem is now much more built up, easier to combine code from other sources for build processes than it was when r.js started.

So set `optimize: 'none'`, then after the r.js build step, run uglify or your preferred minifier on only the files you want to minimize.
