### ISSUE TITLE
Bundles config debugging

### ISSUE THREAD

**Issue by fabienbrooke** [requirejs/r.js#952]
Question: 

I'm using the bundles config feature and would like to know, at the time a new bundle is requested by the running app, what module caused that bundle to be requested. Can someone point me to a line to log out that could help me here?

Thanks

**Comment by jrburke** [comment]
The nameToUrl function converts a module ID to a URL to fetch, and it checks for a bundle ID here: https://github.com/requirejs/requirejs/blob/3e55417e118205553240a4a7ad3aac791065713d/require.js#L1633
