### ISSUE TITLE
Update esprima to 4.0

### ISSUE THREAD

**Issue by marcoscaceres** [requirejs/r.js#963]
I wonder if it might be possible, as a first step towards #959 to update Esprima in r.js? 

Totally guessing here, but given that you can already tell r.js not to Uglify, then one can run Uglify-es separately without r.js crashing on ES6 code?

**Comment by jrburke** [comment]
I ran out of time tonight to release a tagged version of 2.3.4 with this change, but this master snapshot can be used for now:
https://raw.githubusercontent.com/requirejs/r.js/master/dist/r.js

and I should get the tagged release out before next week, ideally tomorrow.

**Comment by marcoscaceres** [comment]
Ha! It totally works 💃🕺  I just set "optimize" to "none" and then manually ran the code through Uglyfy-ES. So excited about this, @jrburke! Can't wait for it to hit RequireJS upstream now.

**Comment by jrburke** [comment]
Just published requirejs 2.3.4 with this fix.
