### ISSUE TITLE
preserveLicenseComments is doubling comments

### ISSUE THREAD

**Issue by elliot-nelson** [requirejs/r.js#964]
## SUMMARY

It looks like there is a clear bug in current r.js, where if `generateSourceMaps` and `preserveLicenseComments` are both set to true, the comments produced in the output file are printed twice.  This causes the generated source map lines to be off by _N_, where _N_ = license comment line count.

## HOW TO REPRODUCE

Clone the current master of `requirejs/r.js`, and run `node dist.js`.

Create an example javascript file, `example.js`:
```
/**
 * @LICENSE
 *
 * I am a license comment.
 */
module.exports = {
    run: function () {
        console.log("I am a program.");
    }
};
```

Now run the following commands:
```
node r.js -o name=example baseUrl=. preserveLicenseComments=true generateSourceMaps=true out=example-out.js
cat example-out.js
cat example-out.js.map
```
The mapfile `sourcesContent` contains the comment as expected, but in the produced source file, the comment is printed twice.  This means attempting to map back from stack traces in production is not possible.

## SOLUTION

The solution, tested locally, seems very simple: at the very bottom of the `uglify` method in `build/jslib/optimize.js`, the `preamble` is being prefixed to the `fileContents`, even though the uglify module has already prefixed it.  Removing this prefix here immediately fixes the problem locally.

I believe this used to work, so perhaps the behavior in the uglify module changed over time.

Would it be possible to get this fixed in r.js?

**Comment by jrburke** [comment]
Fixed by #965.
