### ISSUE TITLE
Generate modules without copying other files

### ISSUE THREAD

**Issue by leog** [requirejs/r.js#970]
Using `out` option is only for optimizing one file. When using `modules` there should be a `dir` option that even though `skipDirOptimize` and `removeCombined` options are set to true, any other file/folder that does not match with `fileExclusionRegExp` will be copied.

I need to just create module files without copying any other file, even vendor. But excluding vendor will result in errors as the optimized modules may depend on them. Including a huge amount of options in the `fileExclusionRegExp` option does not makes sense when maybe setting a `out` on each module maybe makes more sense, or there is a way to enable setting an `out` option for every module as I'm just interested in the optimized modules, and nothing else.

Any idea if this can be done right now without using `fileExclusionRegExp` or maybe makes sense to expect it to be implemented? I can offer my help for a PR.

**Comment by jrburke** [comment]
There are no plans to expand the list of options or behavior of the r.js optimizer. If you want fine-grained control over module tracing and want to only bundle certain things, then [amodro-trace](https://github.com/amodrojs/amodro-trace) is probably a better approach than the r.js optimizer.

Closing as a discussion ticket, but feel free to continue discussion here.
