### ISSUE TITLE
Uglify issue with 2.3.5

### ISSUE THREAD

**Issue by asgoth** [requirejs/r.js#978]
There seems to be an Uglify issue with version 2.3.5

It seems that

    if (typeof someValue !== "undefined") { ... } else { return foo; }

gets compressed to 

    if(void 0===e)return f,...

instead of 

    if('undefined'===e)return f,...

This causes issues on IE10 (and lower). It seems the "unsafe" option is active (which should be false by default). Setting it to false doesn't help.

Sadly the diff is quite large, so not sure which Uglify2 version causes it:
https://github.com/mishoo/UglifyJS2/compare/v2.7.5...v2.8.29

EDIT: it seems adding option "screw_ie8" to false, helps.

See also https://github.com/mishoo/UglifyJS2/issues/2970

**Comment by jrburke** [comment]
I tried to reproduce this by doing the following with the latest master r.js code:

```javascript
// main.js
var someValue = 'something';
(function () {
  if (typeof someValue !== "undefined") { return bar; } else { return foo; }
})();

// build.js
{
    name: 'main',
    out: 'main-built.js'
}
```

And then I ran the build as `node path/to/r.js -o build.js` and the output of the build was:

```javascript
var someValue="something";!function(){void 0!==someValue?bar:foo}(),define("main",function(){});
```

I tried this build config:

```javascript
{
    name: 'main',
    out: 'main-built.js',
    uglify: {
        compress: {
          screw_ie8: false
        },
        mangle: {
          screw_ie8: false
        }
    }
}
```

But it ended in the same result. When I tried with uglifyjs via these steps:

* npm install uglify-js@2.8.29
* `./node_modules/.bin/uglifyjs main.js -c -m

I ended up with this result, which looks the same (except for the `define` call that r.js adds, which is expected):

```javascript
var someValue="something";!function(){void 0!==someValue?bar:foo}();
```

So I believe with latest master code it matches uglify 2.8.29 output. It may be bad for IE 10, but r.js does not seem to be doing extra mangling, seems like an uglifyjs issue.
