### ISSUE TITLE
support one line UMD format

### ISSUE THREAD

**Issue by wkeese** [requirejs/r.js#986]
r.js can't process the one-line UMD format used in https://github.com/uhop/dcl/blob/master/dcl.js, i.e:

```
/* UMD.define */ (typeof define=="function"&&define||function(d,f,m){m={module:module,require:require};module.exports=f.apply(null,d.map(function(n){return m[n]||require(n)}))})
```

The generated layer files don't have the module name in the define() call, i.e. define("dcl/dcl", ..

Is this something r.js should be enhanced to support?   It's probably too hard to support any possible format but this one is trivial to support by just replacing that one line with the word "define".   (Or so I am told.)

**Comment by jrburke** [comment]
Hi @wkeese! As you mention, it is hard to support matching any possible format. The patterns that are used now in r.js favor looking for ones that call `define()` directly, and it was the hope that creating common boilerplate like https://github.com/umdjs/umd would allow for consistency.

This one in particular I feel is harder to support. I would not want to get into the practice of supporting these forms as other folks might have other preferred one-liners, and they could easily change over time.

However, you can support using these files with r.js by using [onBuildRead](https://github.com/requirejs/r.js/blob/master/build/example.build.js#L545) to regexp replace that line with a plain call to `define` that can be identified by the optimizer.

Closing as a discussion ticket, but feel free to continue discussion here.
